add scroll to top in filter panel
overture-stack/dms-ui pull request #165
Opened 2023-06-28 17:40 UTC by samrichca

2023-07-20 14:30 UTC, justincorrigible commented
related to John's question: maybe we can reuse the (svg) icons already in the app?
I could make Arranger expose its own as well, if needed be

2023-07-20 14:34 UTC, joneubank requested changes
Clever implementation thats more flexible than a generic "top of page" scroll.

Some documentation would be great here, plus consider parameterization for working with different child content (z-index, for example).

2023-07-20 14:34 UTC, joneubank commented on components/ScrollToTop.tsx
> +const ScrollToTop = ({ children }: { children: ReactNode }) => {
Can you add a docstring to this component with a description of what it does and an example usage?

Other scroll to top buttons are typically single elements that sit at a fixed position on the screen and scroll to top of page, but this is unique in that it scrolls to the top of the children elements of this component.

2023-07-20 14:34 UTC, joneubank commented on components/ScrollToTop.tsx
> +				z-index: 100;
Since this can accept any children as content, the children may have z-index values beyond 100. Perhaps the z-index can be an optional component parameter so that the dev has control over it?

2023-07-20 16:28 UTC, samrichca commented
updated @joneubank @justincorrigible

2023-07-21 19:49 UTC, justincorrigible approved these changes
lgtm

2023-07-21 20:48 UTC, merged