#26 - warning for mobile users
overture-stack/dms-ui pull request #178
Opened 2023-09-06 18:23 UTC by samrichca

2023-09-07 19:14 UTC, justincorrigible commented on components/pages/explorer/MobileWarning.tsx
> +	const hideMobileWarning = () => setShowMobileWarning(false);
This logic doesn't persist it between sessions. Is this per spec?

2023-09-07 19:15 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +import { useMemo } from 'react';
what's the need for this relocation? may I suggest again we use https://www.npmjs.com/package/prettier-plugin-organize-imports in this repo? (thought i had added it in `develop`)

2023-09-07 19:15 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +import { useMemo } from 'react';
scratch that. this is probably the result of that package

2023-09-07 19:17 UTC, justincorrigible commented on components/pages/explorer/MobileWarning.tsx
> +	return showMobileWarning && NEXT_PUBLIC_SHOW_MOBILE_WARNING ? (
`NEXT_PUBLIC_SHOW_MOBILE_WARNING` is already checked in PageContent
```suggestion

	return showMobileWarning ? (
```

2023-09-11 15:57 UTC, samrichca commented on components/pages/explorer/MobileWarning.tsx
> +	const hideMobileWarning = () => setShowMobileWarning(false);
checked with @patrickdsantos, he wants this to reset on each visit

2023-09-11 17:02 UTC, justincorrigible approved these changes

2023-09-11 18:21 UTC, justincorrigible commented on components/pages/explorer/PageContent.tsx
> +        {NEXT_PUBLIC_SHOW_MOBILE_WARNING && <MobileWarning />}
Looks like the indentation got whacked here?

2023-09-11 18:26 UTC, justincorrigible requested changes
Getting build errors in Jenkins, and indentation got weird after a post-approval commit.
<img width="603" alt="image" src="https://github.com/overture-stack/dms-ui/assets/2107110/8672d918-2156-46c8-a6e0-07dc3e24130d">

Looks like conflicts after merging? 🤷

2023-09-12 14:46 UTC, justincorrigible approved these changes
Let's gooo 🚀

2023-09-12 14:59 UTC, merged