#41 - add jbrowse circular
overture-stack/dms-ui pull request #184
Opened 2023-09-20 17:24 UTC by samrichca

2023-09-20 17:26 UTC, samrichca commented on components/pages/explorer/ActionBar.tsx
> +        {activeTab === RepositoryTabKeys.FILES && (
added keys to tabs because jbrowse tabs have the same display name and different unique keys

2023-09-20 20:38 UTC, samrichca commented on components/theme/getDropdownTheme.ts
> +export const getDropdownTheme = (theme: Theme) => ({
this was on the download dropdown button

2023-09-21 12:30 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +          overflow: hidden !important;
nice catch for something to improve in the DropDown's internal theming. making a ToDo note in the Arranger code

2023-09-21 12:34 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +              left: -2px;
🤔 this tells me there's a `position: absolute` for this list? that doesn't sound ideal.
If so, is the default theme forcing you to do this? I've got to fix that.

2023-09-21 12:40 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +          },
Fix to the need to "left: -2; right: auto", I believe 🤞 
```suggestion
      <MultiSelectDropDown
        align="left"
        theme={{
          ...dropdownTheme,
          width: '140px',
          height: '30px',
          ListWrapper: {
            ...dropdownTheme.ListWrapper,
            css: css`
              width: 7em;
            `,
          },
```

2023-09-21 12:45 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +              (itemLabel === 'Circular View' && !jbrowseCircularError)
`108, 109` and `119, 120` seem opposite of each other, so I think there's a DRY opportunity here if these four lines are abstracted..

2023-09-21 12:47 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseSelectedFilesTable.tsx
> +  const activeJbrowseType = activeTab as JbrowseTypeNames;
There's gotta be a way to not have to assert this type.
@joneubank, help? you're much better at this one.

2023-09-21 12:49 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseWrapper.tsx
> +  const activeJbrowseType = activeTab as JbrowseTypes;
same here for the assertion comment.
`two birds, one stone`?

2023-09-21 12:50 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/types.ts
> +  file_type: JbrowseFileTypes;
nice tightening! 💪

2023-09-21 12:52 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/useJbrowseCompatibility.tsx
> +    callerName: 'Jbrowse - Compatibility Check',
this just helped me realise: are we regressing from tabs? 🙅 
please kindly adjust the linter. we want tabs in all our projects now.

2023-09-21 12:55 UTC, justincorrigible commented on components/pages/explorer/TabsContext.tsx
> +	const [activeTab, setActiveTab] = useState<string | null>(defaultTabs[0]?.key || null);
hmmm methinks the type given into the useState generic here may be the key to not needing `as JbrowseTypes` elsewhere 🤔

2023-09-21 13:00 UTC, justincorrigible commented on components/pages/explorer/TabsContext.tsx
> +	const handleChangeTab = (tabKey: string | null) => {
Naming question as I'm confused, possibly a "me-problem", so no action needed:
what's the semantic difference between `change` and `update`, as seen in these two functions?
One sets Tabs "open", the other sets tabs "active"?

Me being naive and likely wrong, sounds like two functions that could be one and the same, but somehow aren't?

2023-09-21 13:06 UTC, justincorrigible commented on components/pages/explorer/types.ts
> +  JBROWSE_LINEAR = 'jbrowseLinear',
These are already defined in `enum JbrowseTypeNames` at `components/pages/explorer/Jbrowse/utils.tsx`

That other enum could be defined+exported in this file here, and extended into this other enum, to prevent bug-prone type duplication

2023-09-21 13:32 UTC, justincorrigible commented on components/pages/explorer/RepositoryContent.tsx
> +			DropDown: getDropdownTheme(theme),
👍

2023-09-21 13:36 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +import { getDropdownTheme } from '@/components/theme/getDropdownTheme';
Follow-up, after thinking about this one a bit:
rather than importing this in different places, it may be easier to apply all of those DropDown customisations at the global level from `components/theme/components.ts`, like I had done with the `Input` component.

2023-09-21 13:44 UTC, joneubank commented on components/pages/explorer/Jbrowse/JbrowseSelectedFilesTable.tsx
> +  const activeJbrowseType = activeTab as JbrowseTypeNames;
`activeTab` is `string | null` type and should not have this type assertion without checks being done. If the intention is to make it `JbrowseTypeNames` that would require a change to the state maintained in `useTabsContext`

2023-09-21 13:44 UTC, justincorrigible commented on components/pages/explorer/RepositoryContent.tsx
> +		const isVisualizationActive = visualizationTabs.includes(activeTab as RepositoryTabKeys);
and THREE birds with one stone!

2023-09-21 13:46 UTC, justincorrigible requested changes
Nice work overall! and it looked great in demo.

Left a couple tiny requests/comments on things that could be improved to make maintenance easier months in the future when we won't remember as clearly what was happening "today".

2023-09-21 14:03 UTC, joneubank commented on components/pages/explorer/Jbrowse/JbrowseSelectedFilesTable.tsx
> +  const activeJbrowseType = activeTab as JbrowseTypeNames;
Looking at where `activeTab` is used, it seems that we should be writing checks on the value of `activeTab` to make sure it is a valid value from the `JbrowseTypeNames` enum (using a custom type guard), and if it is then we can continue, otherwise this indicates we don't have an expected JBrowse tab and shouldn't render.

A larger change that I would recommend would be to not use the tab selection inside your component rendering code. The selected tab should result in a specific layout Component being rendered, and that layout component can have a fixed type. This is about separating concerns: `activeTab` selects tab layout, tab layout component defines render content. This wouldn't require any value checking.

2023-09-21 14:52 UTC, samrichca commented on components/pages/explorer/Jbrowse/useJbrowseCompatibility.tsx
> +    callerName: 'Jbrowse - Compatibility Check',
not on purpose, I'll update this file

2023-09-21 15:12 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseSelectedFilesTable.tsx
> +  const activeJbrowseType = activeTab as JbrowseTypeNames;
I get what you mean, I'll brainstorm some solutions. thank you for the feedback

2023-09-21 17:25 UTC, samrichca commented on components/pages/explorer/TabsContext.tsx
> +	const handleChangeTab = (tabKey: string | null) => {
changing from tab A to tab B vs. updating the properties of tab A

i think i'm gonna change up how this is handled though

2023-09-21 18:12 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +import { getDropdownTheme } from '@/components/theme/getDropdownTheme';
do you know what the component name would be called for this?

MultiSelectDropDown & DropDown not working atm

2023-09-21 18:29 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +import { getDropdownTheme } from '@/components/theme/getDropdownTheme';
odd! it should be working with `DropDown` (unless maybe the props passed directly to the component are overriding the theme?)
![image](https://github.com/overture-stack/dms-ui/assets/2107110/b5140a2b-b514-4ffc-973b-e6c61d625132)

2023-09-21 18:36 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +              disabled={!error}
much better!thanks for making this change.

Not for this PR, but I do wish we could redesign the CustomTooltip to be "shown" instead, as "disabled" is technically its default state lol

2023-09-21 18:37 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +                disabled={jbrowseLoading || !!error}
there shouldn't be a need for `!!` here. `error` is already a boolean

2023-09-21 19:29 UTC, joneubank requested changes
I added more commentary around type assertions being problematic, we need to be very conscientious of where those are used as they circumvent the value of having TS do the type checking.

Couple other suggestions but nothing too urgent.

2023-09-21 19:29 UTC, joneubank commented on components/pages/explorer/TabsContext.tsx
>  	activeTab: string | null;
why are we using `null` instead of just an optional string? I would simplify this to be `activeTab?: string` making further types `string | undefined`.

Moreover, you could simplify a lot of downstream code by making this value from a tabs keys list (like your enum) instead of a generic string.

```ts
export type TabName = 'arrangerTable' | 'jbrowseLinear' | 'jbrowseCircular';
export interface TabsContextInterface {
	activeTab: TabName;
        // ...
}
```

2023-09-21 19:29 UTC, joneubank commented on components/pages/explorer/types.ts
> +  JBROWSE_LINEAR = 'jbrowseLinear',
Its ok to separate Tab keys from Jbrowse display types. They have separate meanings. Imagine a tab with BOTH jbrowse views and you can see the separation needed between jbrowse components and tab layouts.

2023-09-21 19:29 UTC, joneubank commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +            (itemLabel === 'Circular View' && jbrowseCircularError);
This isn't a problem here, but for consideration on larger builds:
We want to separate the use of display text from action selection. Each label should have a string literal used as an action key (ex. `linearView`, `circularView`) and separate display text (consider case where we need language translations).

2023-09-21 19:47 UTC, joneubank commented on components/pages/explorer/TabsContext.tsx
>  	activeTab: string | null;
Expanding on the above now that I've seen your `RepositoryTabKeys` enum... those are the values used in the DMS, so maybe thats the value to use as this type?

If the tab system is meant to be a generic/reusable component, you can make the context take a generic value that includes the list of tabs available... I'll whip up an example refactor to show.

2023-09-22 12:07 UTC, justincorrigible commented on components/pages/explorer/types.ts
> +  JBROWSE_LINEAR = 'jbrowseLinear',
"stealth edit" 😆 

I'd further argue, "don't use TS Enums"? but that may be beyond the scope of this PR.

2023-09-22 12:09 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/utils.tsx
> +export enum JbrowseTypeNames {
you mean "in contrast to Arrays having plural names, e.g. Items", right?

wasn't aware of that one, good to know! 🙏

2023-09-22 12:18 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +            (itemLabel === 'Circular View' && jbrowseCircularError);
Good point! Took me a couple reads to gather what you meant, and I agree now.
Wouldn't have called that myself but it's a quite practical idea.

2023-09-22 14:59 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +import { getDropdownTheme } from '@/components/theme/getDropdownTheme';
![image](https://github.com/overture-stack/dms-ui/assets/3540896/3d3b3d46-7401-468e-a6c8-cb50ebc162b6)
![image](https://github.com/overture-stack/dms-ui/assets/3540896/5034eefb-842b-4c7c-b9a0-d38491bb5990)
![image](https://github.com/overture-stack/dms-ui/assets/3540896/410e7692-a960-4f32-be4f-330361119188)

no luck unfortunately

2023-09-22 15:19 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +import { getDropdownTheme } from '@/components/theme/getDropdownTheme';
🤔 that is truly odd. let's park that for another PR, as this is important but not urgent
could I bug you to make a ticket for it in this repo, and assigning it to me?

2023-09-22 16:33 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +            (itemLabel === 'Circular View' && jbrowseCircularError);
I'm not sure how to do that here because this component only takes strings... I'm sure there's a way (the string could be the key for translation) but not a priority for an english-only project

`itemToString={(itemLabel: JbrowseTitles, closeDropDownFn) => {`

2023-09-26 16:45 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +						(itemLabel === 'Circular View' && jbrowseCircularError);
one last request: abstract these as reusable constants, if they don’t already exist.

2023-09-26 17:03 UTC, justincorrigible approved these changes
great work, Sam! 🎉
I’ll approve this PR, yet would like to see those strings be made reusable constants to prevent bugs if this tabs thing is ever extended.


Btw, it seems the PR is not passing Jenkins.

2023-09-27 21:30 UTC, samrichca commented on components/pages/explorer/RepositoryTabsContext.tsx
> +} as unknown as RepositoryTabsContextInterface);
has a TS error without 'as unknown as x'. we had this on another context provider before

2023-09-27 21:45 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +								onClick={() => {
ToDo for the future (fine for this PR?): abstract this inline function from the component's return.
instantiation of new functions on every re-render is bad practice.

2023-09-27 21:48 UTC, justincorrigible commented on components/pages/explorer/RepositoryTabsContext.tsx
> +} as unknown as RepositoryTabsContextInterface);
I'll let @joneubank chime in on that one first, but I'm confident there's a more maintainable way to handle this.

2023-09-28 01:03 UTC, samrichca commented on components/pages/explorer/RepositoryTabsContext.tsx
> +} as unknown as RepositoryTabsContextInterface);
I mixed this up, I used unknown with the tables. there must be a fix here since it worked before without it, but I'm stumped at the moment

2023-09-28 13:35 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +								onClick={() => handleJbrowseOption(itemLabel, closeDropDownFn)}
oh! you went for it in this PR, nice!

this approach is close, but not quite the right solution, as it still creates a new arrow with every render.
I'll open a PR onto this branch to show what I mean.

2023-09-28 13:38 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +								onClick={() => handleJbrowseOption(itemLabel, closeDropDownFn)}
ok, not sure how to do this and pass in arguments that aren't attached to the event

2023-09-28 13:44 UTC, justincorrigible commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +								onClick={() => handleJbrowseOption(itemLabel, closeDropDownFn)}
good question! like so https://github.com/overture-stack/dms-ui/pull/188

2023-09-28 15:51 UTC, joneubank commented on components/pages/explorer/RepositoryTabsContext.tsx
> +} as unknown as RepositoryTabsContextInterface);
I know youre fixing this but I just want to respond that there is no reason to have double type assertion. In this case we shouldn't be faking our type, instead just provide default values that match the expected type. We overwrite these in the tab implementation immediately anyways:

```ts
export const RepositoryTabsContext = createContext<RepositoryTabsContextInterface>({
	handleSwitchTab: () => {},
	handleCloseTab: () => {},
	handleOpenTab: () => {},
	handleUpdateTab: () => {},
	openTabs: [],
});
```

2023-09-28 17:18 UTC, justincorrigible approved these changes
LGTM!

2023-09-28 17:19 UTC, samrichca commented on components/pages/explorer/Jbrowse/JbrowseLaunchButton.tsx
> +								onClick={() => handleJbrowseOption(itemLabel, closeDropDownFn)}
decided to leave it as an arrow function due to event typing issues

2023-09-29 13:43 UTC, joneubank approved these changes

2023-09-29 19:05 UTC, merged