💄 32 - UI feedback
overture-stack/dms-ui pull request #76
Opened 2021-03-11 15:42 UTC by anncatton

2021-03-12 21:14 UTC, joneubank requested changes

2021-03-12 21:14 UTC, joneubank commented on components/NavBar.tsx
> +        height: ${NAVBAR_HEIGHT}px;
why isn't this a property in theme?

2021-03-12 21:14 UTC, joneubank commented on components/pages/explorer/PageContent.tsx
> +} from '../../../global/utils/constants';
Is this an existing pattern or did you introduce this? These feel like values that usually get shared to CSS via the theme object.

2021-03-12 21:14 UTC, joneubank commented on global/utils/constants.ts
> +export const NAVBAR_HEIGHT = 50;
Repeating comment about css properties belonging in theme.

2021-03-15 20:48 UTC, joneubank requested changes
Thanks for updates. You can get rid of the consts now.

2021-03-15 20:48 UTC, joneubank commented on components/theme/dimensions.ts
> +export const NAVBAR_HEIGHT = 50;
we can get rid of these, ya?

2021-03-15 20:49 UTC, anncatton commented on components/theme/dimensions.ts
> +export const NAVBAR_HEIGHT = 50;
oh whoops i thought i did. derp

2021-03-15 20:53 UTC, joneubank approved these changes
j'approve

2021-03-15 20:55 UTC, merged